
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      filter:
        preserve-host-header:
          enabled: true
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin, RETAIN_UNIQUE
        - AddResponseHeader=Access-Control-Allow-Origin, *
        - SetStatus=200
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedHeaders: "*"
            allowedMethods:
              - GET
              - POST
              - HEAD
              - PUT
              - DELETE
              - OPTIONS
        add-to-simple-url-handler-mapping: true
      x-forwarded:
        enabled: true


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
      instance:
        instanceId: ${spring.application.name}:${server.port}

server:
  port: 8090